name: build
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: test
      env:
        GCP_PROJECT: github_actions
        COVERALLS_REPO_TOKEN:  ${{ secrets.COVERALLS_REPO_TOKEN }}  
      run: |
        coverage run --source=. -m unittest main_test.py
        coveralls
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: |
        gcloud functions deploy github-protect-branch \
          --project=github-protect-branch \
          --region=us-central1 \
          --runtime=python37 \
          --service-account=github-protect-branch@appspot.gserviceaccount.com \
          --source=https://source.developers.google.com/projects/github-protect-branch/repos/github_paper-street-soap-co_github-branch-protect/moveable-aliases/master/paths// \
          --entry-point=repository_event_http
